version: '3'
services:
  client: 
    container_name: service_client
    build: 
      dockerfile: Dockerfile.dev
      context: './skeleton-react'
    volumes:
      - /app/node_modules
      - ./skeleton-react:/app
    ports:
    - '3000:3000'
  api:
    container_name:  service_api
    build: 
      dockerfile: Dockerfile.dev
      context: './server'
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '5000:5000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    container_name:  service_redis
    image: 'redis:latest'
    logging:
      driver: none
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
